<a href="https://colab.research.google.com/github/shreyaskp150/Bootcamp_frontend2020/blob/master/Lec1_PHD.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
from sklearn import datasets
iris = datasets.load_iris()
X = iris.data 
y = iris.target

In [ ]:
from sklearn.model_selection import train_test_split
X_train , X_test , y_train , y_test = train_test_split (X, y, test_size = 0.20)

In [ ]:
from sklearn.preprocessing import StandardScaler
standard_scaler = StandardScaler()
# sc = standard_scaler.fit(X_train)
X_train = standard_scaler.transform(X_train)
X_test = standard_scaler.transform(X_test)

In [ ]:
from sklearn.linear_model import LogisticRegression

# Create an instance of Logistic Regression Classifier and fit the data.
LR = LogisticRegression()
LR.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [ ]:
LR_pred_test = LR.predict(X_test)

In [ ]:
LR_pred_train = LR.predict(X_train)

In [ ]:
from sklearn.metrics import accuracy_score
LR_acc_test = accuracy_score(LR_pred_test,y_test ) # testing data
LR_acc_train = accuracy_score(LR_pred_train,y_train ) # training data

In [ ]:
print(" Testing Accuracy of LR model is %s " % LR_acc_test)
print(" Training Accuracy of LR model is %s " % LR_acc_train)

 Testing Accuracy of LR model is 0.9333333333333333 
 Training Accuracy of LR model is 0.9833333333333333 


In [ ]:
LR.get_params(deep=True)

{'C': 1.0,
 'class_weight': None,
 'dual': False,
 'fit_intercept': True,
 'intercept_scaling': 1,
 'l1_ratio': None,
 'max_iter': 100,
 'multi_class': 'auto',
 'n_jobs': None,
 'penalty': 'l2',
 'random_state': None,
 'solver': 'lbfgs',
 'tol': 0.0001,
 'verbose': 0,
 'warm_start': False}

In [ ]:
LR.coef_

array([[-0.99846807,  1.30909386, -1.71818222, -1.62543048],
       [ 0.52900861, -0.41196802, -0.36289402, -0.80601756],
       [ 0.46945947, -0.89712584,  2.08107624,  2.43144804]])

In [ ]:
LR.intercept_

array([-0.1606404 ,  1.90463645, -1.74399605])

In [ ]:
sample = np.array( [[20], [20], [12.5], [17]])
sample.shape


(4, 1)

In [ ]:
np.c_[sample].shape


(4, 1)

In [ ]:
f = np.transpose(sample)
print(f.shape)
LR.predict(f)

(1, 4)


array([2])

In [ ]:
LR.predict_proba(f)

array([[3.33768451e-44, 1.39985142e-31, 1.00000000e+00]])

In [ ]:
# Scaling new data before prediction 
std = sc.scale_
mean = sc.mean_
print(std)
print(mean)


[0.82203634 0.45328355 1.74742489 0.7586611 ]
[5.8225     3.04416667 3.7275     1.19      ]


In [ ]:
g = sc.transform(f)
print(g)

[[17.24680437 37.4066818   5.02024439 20.83934444]]


In [ ]:
LR.predict_proba(g)

array([[3.41938875e-20, 1.92023496e-25, 1.00000000e+00]])